om_administration:
    resource: "@OMAdministrationBundle/Resources/config/routing.yml"
    prefix:   /

om_localisation:
    resource: "@OMLocalisationBundle/Resources/config/routing.yml"
    prefix:   /

om_espace_user:
    resource: "@OMEspaceUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# app/config/routing.yml
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"


user_api_demos:
    type: rest
    resource: OM\EspaceUserBundle\Controller\DemoController

#tag rest
tag:
    resource: "@OMAdministrationBundle/Controller/TagController.php"
    prefix:   /
    type:     rest
#not rest
notts:
    resource: "@OMAdministrationBundle/Controller/NotificationController.php"
    prefix:   /
    type:     rest
#session rest
session:
    resource: "@OMAuthBundle/Controller/SessionController.php"
    prefix:   /
    type:     rest

#circuit rest
circuit:
    resource: "@OMLocalisationBundle/Controller/CircuitController.php"
    prefix:   /
    type:     rest
#follow rest
follow:
    resource: "@OMLocalisationBundle/Controller/FollowController.php"
    prefix:   /
    type:     rest

#source rest
source:
    resource: "@OMAdministrationBundle/Controller/SourceController.php"
    prefix:   /
    type:     rest


#note rest
note:
    resource: "@OMAdministrationBundle/Controller/NoteController.php"
    prefix:   /
    type:     rest

#rdv rest
contract:
    resource: "@OMAdministrationBundle/Controller/RdvController.php"
    prefix:   /
    type:     rest
#contrat rest
rdv:
    resource: "@OMAdministrationBundle/Controller/ContractController.php"
    prefix:   /
    type:     rest

#modalité de paiement rest
pmodality:
    resource: "@OMAdministrationBundle/Controller/PmodalityController.php"
    prefix:   /
    type:     rest

#mode de paiement rest
pmode:
    resource: "@OMAdministrationBundle/Controller/PmodeController.php"
    prefix:   /
    type:     rest

#offre rest
offre:
    resource: "@OMAdministrationBundle/Controller/OffreController.php"
    prefix:   /
    type:     rest
#meeting rest
meeting:
    resource: "@OMAdministrationBundle/Controller/MeetingController.php"
    prefix:   /
    type:     rest
city:
    resource: "@OMAdministrationBundle/Controller/CityController.php"
    prefix:   /
    type:     rest
gov:
    resource: "@OMAdministrationBundle/Controller/GouverneraController.php"
    prefix:   /
    type:     rest

#registration rest
registration:
    resource: "@OMEspaceUserBundle/Controller/RegistrationController.php"
    prefix:   /
    type:     rest

#sticky rest
sticky:
     resource: "@OMAdministrationBundle/Controller/StickyController.php"
     prefix:   /
     type:     rest

#task rest
task:
     resource: "@OMAdministrationBundle/Controller/TaskController.php"
     prefix:   /
     type:     rest

#affect rest
afectation_client:
     resource: "@OMEspaceUserBundle/Controller/UserController.php"
     prefix:   /
     type:     rest

#product rest
product:
     resource: "@OMAdministrationBundle/Controller/ProductController.php"
     prefix:   /
     type:     rest

#access rest
access:
    resource: "@OMAdministrationBundle/Controller/AccessController.php"
    prefix:   /
    type: rest